// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V3.Item.Events
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\{domain_name}\events
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Item.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/{domain_name}/events{?ascending*,attachment*,begin*,end*,event*,from*,limit*,list*,message%2Did*,recipient*,recipients*,severity*,size*,subject*,tags*,to*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Item.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/{domain_name}/events{?ascending*,attachment*,begin*,end*,event*,from*,limit*,list*,message%2Did*,recipient*,recipients*,severity*,size*,subject*,tags*,to*}", rawUrl)
        {
        }
        /// <summary>
        /// Mailgun tracks every inbound and outbound message event and retains this data for at least 3 days.See [Filter expression](https://documentation.mailgun.com/docs/mailgun/user-manual/events/#filter-expression) for details about filtering expressions
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Get_v3_domain_name_events_200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.Get_v3_domain_name_events_200?> GetAsync(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V3.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.Get_v3_domain_name_events_200> GetAsync(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V3.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Mailgun.OpenApiClient.Models.Get_v3_domain_name_events_200>(requestInfo, global::Soenneker.Mailgun.OpenApiClient.Models.Get_v3_domain_name_events_200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Mailgun tracks every inbound and outbound message event and retains this data for at least 3 days.See [Filter expression](https://documentation.mailgun.com/docs/mailgun/user-manual/events/#filter-expression) for details about filtering expressions
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V3.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V3.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Item.Events.EventsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Mailgun.OpenApiClient.V3.Item.Events.EventsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Mailgun.OpenApiClient.V3.Item.Events.EventsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Mailgun tracks every inbound and outbound message event and retains this data for at least 3 days.See [Filter expression](https://documentation.mailgun.com/docs/mailgun/user-manual/events/#filter-expression) for details about filtering expressions
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EventsRequestBuilderGetQueryParameters 
        {
            /// <summary>Sort direction by time. Must be provided if the range end time is not specified. Can be either yes or no</summary>
            [QueryParameter("ascending")]
            public global::Soenneker.Mailgun.OpenApiClient.V3.Item.Events.GetAscendingQueryParameterType? Ascending { get; set; }
            /// <summary>Filter by the name of an attached file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("attachment")]
            public string? Attachment { get; set; }
#nullable restore
#else
            [QueryParameter("attachment")]
            public string Attachment { get; set; }
#endif
            /// <summary>The beginning of the search time range in epoch seconds</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("begin")]
            public string? Begin { get; set; }
#nullable restore
#else
            [QueryParameter("begin")]
            public string Begin { get; set; }
#endif
            /// <summary>The end of the search time range in epoch seconds</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("end")]
            public string? End { get; set; }
#nullable restore
#else
            [QueryParameter("end")]
            public string End { get; set; }
#endif
            /// <summary>Filter by event type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("event")]
            public string? Event { get; set; }
#nullable restore
#else
            [QueryParameter("event")]
            public string Event { get; set; }
#endif
            /// <summary>Filter by email address mentioned in the From MIME header</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("from")]
            public string? From { get; set; }
#nullable restore
#else
            [QueryParameter("from")]
            public string From { get; set; }
#endif
            /// <summary>The number of entries to return (300 max)</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Filter by mailing list email address that message was originally sent to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("list")]
            public string? List { get; set; }
#nullable restore
#else
            [QueryParameter("list")]
            public string List { get; set; }
#endif
            /// <summary>Filter by Mailgun message id returned by the messages API</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("message%2Did")]
            public string? MessageId { get; set; }
#nullable restore
#else
            [QueryParameter("message%2Did")]
            public string MessageId { get; set; }
#endif
            /// <summary>Filter by email address of a recipient. While messages are addressable to one or more recipients, each event (with one exception) tracks one recipient. See stored events for use of recipients</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("recipient")]
            public string? Recipient { get; set; }
#nullable restore
#else
            [QueryParameter("recipient")]
            public string Recipient { get; set; }
#endif
            /// <summary>Specific to stored events, this field tracks all of the potential message recipients.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("recipients")]
            public string? Recipients { get; set; }
#nullable restore
#else
            [QueryParameter("recipients")]
            public string Recipients { get; set; }
#endif
            /// <summary>Filter by event severity, if exists. Currently for failed events only. See [Tracking Failures](https://documentation.mailgun.com/docs/mailgun/user-manual/tracking-messages/#tracking-failures)</summary>
            [QueryParameter("severity")]
            public global::Soenneker.Mailgun.OpenApiClient.Models.EventSeverityType? Severity { get; set; }
            /// <summary>Filter by message size. Mostly intended to be used with range filtering expressions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("size")]
            public string? Size { get; set; }
#nullable restore
#else
            [QueryParameter("size")]
            public string Size { get; set; }
#endif
            /// <summary>Filter by subject line</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("subject")]
            public string? Subject { get; set; }
#nullable restore
#else
            [QueryParameter("subject")]
            public string Subject { get; set; }
#endif
            /// <summary>Filter by user defined tags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tags")]
            public string? Tags { get; set; }
#nullable restore
#else
            [QueryParameter("tags")]
            public string Tags { get; set; }
#endif
            /// <summary>Filter by email address mentioned in the To MIME header</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("to")]
            public string? To { get; set; }
#nullable restore
#else
            [QueryParameter("to")]
            public string To { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
