// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.V3.Ip_pools.Item.Ips.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V3.Ip_pools.Item.Ips
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\ip_pools\{pool_id}\ips
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IpsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Mailgun.OpenApiClient.v3.ip_pools.item.ips.item collection</summary>
        /// <param name="position">IP to add to the DIPP</param>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Ip_pools.Item.Ips.Item.WithIpItemRequestBuilder"/></returns>
        public global::Soenneker.Mailgun.OpenApiClient.V3.Ip_pools.Item.Ips.Item.WithIpItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("ip", position);
                return new global::Soenneker.Mailgun.OpenApiClient.V3.Ip_pools.Item.Ips.Item.WithIpItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Ip_pools.Item.Ips.IpsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IpsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/ip_pools/{pool_id}/ips", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Ip_pools.Item.Ips.IpsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IpsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/ip_pools/{pool_id}/ips", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
