// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.V1.Alerts.Email;
using Soenneker.Mailgun.OpenApiClient.V1.Alerts.Events;
using Soenneker.Mailgun.OpenApiClient.V1.Alerts.Settings;
using Soenneker.Mailgun.OpenApiClient.V1.Alerts.Slack;
using Soenneker.Mailgun.OpenApiClient.V1.Alerts.Webhooks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V1.Alerts
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\alerts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AlertsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The email property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.Email.EmailRequestBuilder Email
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.Settings.SettingsRequestBuilder Settings
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The slack property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.Slack.SlackRequestBuilder Slack
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.Slack.SlackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.AlertsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AlertsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/alerts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V1.Alerts.AlertsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AlertsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/alerts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
