// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V1.Dynamic_pools.Domains
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSort_orderQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ascending")]
        #pragma warning disable CS1591
        Ascending,
        #pragma warning restore CS1591
        [EnumMember(Value = "descending")]
        #pragma warning disable CS1591
        Descending,
        #pragma warning restore CS1591
    }
}
