// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Entities.Item.Rules;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Entities.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\bounce-classification\domains\{domain}\entities\{entityId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEntityItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The rules property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Entities.Item.Rules.RulesRequestBuilder Rules
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Entities.Item.Rules.RulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Entities.Item.WithEntityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/bounce-classification/domains/{domain}/entities/{entityId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Entities.Item.WithEntityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/bounce-classification/domains/{domain}/entities/{entityId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
