// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.V5.Accounts.Subaccounts.Ip_pools.All;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V5.Accounts.Subaccounts.Ip_pools
{
    /// <summary>
    /// Builds and executes requests for operations under \v5\accounts\subaccounts\ip_pools
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Ip_poolsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Subaccounts.Ip_pools.All.AllRequestBuilder All
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Subaccounts.Ip_pools.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Subaccounts.Ip_pools.Ip_poolsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Ip_poolsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v5/accounts/subaccounts/ip_pools", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Subaccounts.Ip_pools.Ip_poolsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Ip_poolsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v5/accounts/subaccounts/ip_pools", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
