// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.Countries;
using Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.Devices;
using Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.Providers;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\domains\{domainName-id}\tag
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TagRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The countries property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.Countries.CountriesRequestBuilder Countries
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The devices property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.Devices.DevicesRequestBuilder Devices
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.Devices.DevicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The providers property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.Providers.ProvidersRequestBuilder Providers
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.Providers.ProvidersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.TagRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/domains/{domainName%2Did}/tag", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Domains.Item.Tag.TagRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/domains/{domainName%2Did}/tag", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
