// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.Models;
using Soenneker.Mailgun.OpenApiClient.V5.Accounts.Features;
using Soenneker.Mailgun.OpenApiClient.V5.Accounts.Http_signing_key;
using Soenneker.Mailgun.OpenApiClient.V5.Accounts.Limit;
using Soenneker.Mailgun.OpenApiClient.V5.Accounts.Resend_activation_email;
using Soenneker.Mailgun.OpenApiClient.V5.Accounts.Subaccounts;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V5.Accounts
{
    /// <summary>
    /// Builds and executes requests for operations under \v5\accounts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The features property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Features.FeaturesRequestBuilder Features
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Features.FeaturesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The http_signing_key property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Http_signing_key.Http_signing_keyRequestBuilder Http_signing_key
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Http_signing_key.Http_signing_keyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The limit property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Limit.LimitRequestBuilder Limit
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Limit.LimitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resend_activation_email property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Resend_activation_email.Resend_activation_emailRequestBuilder Resend_activation_email
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Resend_activation_email.Resend_activation_emailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subaccounts property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Subaccounts.SubaccountsRequestBuilder Subaccounts
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.Subaccounts.SubaccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.AccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v5/accounts{?absolute_session_timeout*,inactive_session_timeout*,logout_redirect_url*,name*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.AccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v5/accounts{?absolute_session_timeout*,inactive_session_timeout*,logout_redirect_url*,name*}", rawUrl)
        {
        }
        /// <summary>
        /// Update variable account settings
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunAccountsApiGenericMessage"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunAccountsApiGenericMessage">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunAccountsApiGenericMessage?> PutAsync(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.AccountsRequestBuilder.AccountsRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunAccountsApiGenericMessage> PutAsync(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.AccountsRequestBuilder.AccountsRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunAccountsApiGenericMessage.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunAccountsApiGenericMessage>(requestInfo, global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunAccountsApiGenericMessage.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update variable account settings
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.AccountsRequestBuilder.AccountsRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.AccountsRequestBuilder.AccountsRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.AccountsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.AccountsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Mailgun.OpenApiClient.V5.Accounts.AccountsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Update variable account settings
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AccountsRequestBuilderPutQueryParameters 
        {
            /// <summary>The login session timeout period limit</summary>
            [QueryParameter("absolute_session_timeout")]
            public int? AbsoluteSessionTimeout { get; set; }
            /// <summary>The login session timeout period for inactivity</summary>
            [QueryParameter("inactive_session_timeout")]
            public int? InactiveSessionTimeout { get; set; }
            /// <summary>The url to redirect to upon logout</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("logout_redirect_url")]
            public string? LogoutRedirectUrl { get; set; }
#nullable restore
#else
            [QueryParameter("logout_redirect_url")]
            public string LogoutRedirectUrl { get; set; }
#endif
            /// <summary>The new account organization name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
