// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetV1DynamicPoolsDomainsSortByParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "bounce_rate")]
        #pragma warning disable CS1591
        BounceRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "complaint_rate")]
        #pragma warning disable CS1591
        ComplaintRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
    }
}
