// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Github_com_mailgun_logs_api_pkg_api_model_Flags : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The isAmp property</summary>
        public bool? IsAmp { get; set; }
        /// <summary>The isAuthenticated property</summary>
        public bool? IsAuthenticated { get; set; }
        /// <summary>The isCallback property</summary>
        public bool? IsCallback { get; set; }
        /// <summary>The isDelayedBounce property</summary>
        public bool? IsDelayedBounce { get; set; }
        /// <summary>The isEncrypted property</summary>
        public bool? IsEncrypted { get; set; }
        /// <summary>The isRouted property</summary>
        public bool? IsRouted { get; set; }
        /// <summary>The isSystemTest property</summary>
        public bool? IsSystemTest { get; set; }
        /// <summary>The isTestMode property</summary>
        public bool? IsTestMode { get; set; }
        /// <summary>The isWebhook property</summary>
        public bool? IsWebhook { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_logs_api_pkg_api_model_Flags"/> and sets the default values.
        /// </summary>
        public Github_com_mailgun_logs_api_pkg_api_model_Flags()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_logs_api_pkg_api_model_Flags"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_logs_api_pkg_api_model_Flags CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_logs_api_pkg_api_model_Flags();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "is-amp", n => { IsAmp = n.GetBoolValue(); } },
                { "is-authenticated", n => { IsAuthenticated = n.GetBoolValue(); } },
                { "is-callback", n => { IsCallback = n.GetBoolValue(); } },
                { "is-delayed-bounce", n => { IsDelayedBounce = n.GetBoolValue(); } },
                { "is-encrypted", n => { IsEncrypted = n.GetBoolValue(); } },
                { "is-routed", n => { IsRouted = n.GetBoolValue(); } },
                { "is-system-test", n => { IsSystemTest = n.GetBoolValue(); } },
                { "is-test-mode", n => { IsTestMode = n.GetBoolValue(); } },
                { "is-webhook", n => { IsWebhook = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("is-amp", IsAmp);
            writer.WriteBoolValue("is-authenticated", IsAuthenticated);
            writer.WriteBoolValue("is-callback", IsCallback);
            writer.WriteBoolValue("is-delayed-bounce", IsDelayedBounce);
            writer.WriteBoolValue("is-encrypted", IsEncrypted);
            writer.WriteBoolValue("is-routed", IsRouted);
            writer.WriteBoolValue("is-system-test", IsSystemTest);
            writer.WriteBoolValue("is-test-mode", IsTestMode);
            writer.WriteBoolValue("is-webhook", IsWebhook);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
