// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    /// <summary>Metric</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GithubComMailgunAnalyticsClientGolangMetric
    {
        [EnumMember(Value = "accepted_incoming_count")]
        #pragma warning disable CS1591
        AcceptedIncomingCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "accepted_outgoing_count")]
        #pragma warning disable CS1591
        AcceptedOutgoingCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "accepted_count")]
        #pragma warning disable CS1591
        AcceptedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered_smtp_count")]
        #pragma warning disable CS1591
        DeliveredSmtpCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered_http_count")]
        #pragma warning disable CS1591
        DeliveredHttpCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered_optimized_count")]
        #pragma warning disable CS1591
        DeliveredOptimizedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered_count")]
        #pragma warning disable CS1591
        DeliveredCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "processed_count")]
        #pragma warning disable CS1591
        ProcessedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "sent_count")]
        #pragma warning disable CS1591
        SentCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "opened_count")]
        #pragma warning disable CS1591
        OpenedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "clicked_count")]
        #pragma warning disable CS1591
        ClickedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "unique_opened_count")]
        #pragma warning disable CS1591
        UniqueOpenedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "unique_clicked_count")]
        #pragma warning disable CS1591
        UniqueClickedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribed_count")]
        #pragma warning disable CS1591
        UnsubscribedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "complained_count")]
        #pragma warning disable CS1591
        ComplainedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed_count")]
        #pragma warning disable CS1591
        FailedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "temporary_failed_count")]
        #pragma warning disable CS1591
        TemporaryFailedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "permanent_failed_count")]
        #pragma warning disable CS1591
        PermanentFailedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "temporary_failed_esp_block_count")]
        #pragma warning disable CS1591
        TemporaryFailedEspBlockCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "permanent_failed_esp_block_count")]
        #pragma warning disable CS1591
        PermanentFailedEspBlockCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "webhook_count")]
        #pragma warning disable CS1591
        WebhookCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "rate_limit_count")]
        #pragma warning disable CS1591
        RateLimitCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "permanent_failed_optimized_count")]
        #pragma warning disable CS1591
        PermanentFailedOptimizedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "permanent_failed_old_count")]
        #pragma warning disable CS1591
        PermanentFailedOldCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "bounced_count")]
        #pragma warning disable CS1591
        BouncedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "hard_bounces_count")]
        #pragma warning disable CS1591
        HardBouncesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "soft_bounces_count")]
        #pragma warning disable CS1591
        SoftBouncesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "delayed_bounce_count")]
        #pragma warning disable CS1591
        DelayedBounceCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "suppressed_bounces_count")]
        #pragma warning disable CS1591
        SuppressedBouncesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "suppressed_unsubscribed_count")]
        #pragma warning disable CS1591
        SuppressedUnsubscribedCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "suppressed_complaints_count")]
        #pragma warning disable CS1591
        SuppressedComplaintsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered_first_attempt_count")]
        #pragma warning disable CS1591
        DeliveredFirstAttemptCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "delayed_first_attempt_count")]
        #pragma warning disable CS1591
        DelayedFirstAttemptCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered_two_plus_attempts_count")]
        #pragma warning disable CS1591
        DeliveredTwoPlusAttemptsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered_rate")]
        #pragma warning disable CS1591
        DeliveredRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "opened_rate")]
        #pragma warning disable CS1591
        OpenedRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "clicked_rate")]
        #pragma warning disable CS1591
        ClickedRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "unique_opened_rate")]
        #pragma warning disable CS1591
        UniqueOpenedRate1,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribed_rate")]
        #pragma warning disable CS1591
        UnsubscribedRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "complained_rate")]
        #pragma warning disable CS1591
        ComplainedRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "bounce_rate")]
        #pragma warning disable CS1591
        BounceRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "permanent_fail_rate")]
        #pragma warning disable CS1591
        PermanentFailRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "temporary_fail_rate")]
        #pragma warning disable CS1591
        TemporaryFailRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "delayed_rate")]
        #pragma warning disable CS1591
        DelayedRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "delayed_first_attempt_rate")]
        #pragma warning disable CS1591
        DelayedFirstAttemptRate,
        #pragma warning restore CS1591
    }
}
