// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Github_com_mailgun_bounce_classification_entities_MetricsCountsAndRates : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Total bounces and delays</summary>
        public long? ClassifiedFailuresCount { get; set; }
        /// <summary>The critical_bounce_count property</summary>
        public long? CriticalBounceCount { get; set; }
        /// <summary>Percentages; null for Spam Filters</summary>
        public long? CriticalBounceRate { get; set; }
        /// <summary>The critical_delay_count property</summary>
        public long? CriticalDelayCount { get; set; }
        /// <summary>Percentages; null for Spam Filters</summary>
        public long? CriticalDelayRate { get; set; }
        /// <summary>null for Spam Filters</summary>
        public long? DeliveredSmtpCount { get; set; }
        /// <summary>The non_critical_bounce_count property</summary>
        public long? NonCriticalBounceCount { get; set; }
        /// <summary>Percentages; null for Spam Filters</summary>
        public long? NonCriticalBounceRate { get; set; }
        /// <summary>The non_critical_delay_count property</summary>
        public long? NonCriticalDelayCount { get; set; }
        /// <summary>Percentages; null for Spam Filters</summary>
        public long? NonCriticalDelayRate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_MetricsCountsAndRates"/> and sets the default values.
        /// </summary>
        public Github_com_mailgun_bounce_classification_entities_MetricsCountsAndRates()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_MetricsCountsAndRates"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_MetricsCountsAndRates CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_MetricsCountsAndRates();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "classified_failures_count", n => { ClassifiedFailuresCount = n.GetLongValue(); } },
                { "critical_bounce_count", n => { CriticalBounceCount = n.GetLongValue(); } },
                { "critical_bounce_rate", n => { CriticalBounceRate = n.GetLongValue(); } },
                { "critical_delay_count", n => { CriticalDelayCount = n.GetLongValue(); } },
                { "critical_delay_rate", n => { CriticalDelayRate = n.GetLongValue(); } },
                { "delivered_smtp_count", n => { DeliveredSmtpCount = n.GetLongValue(); } },
                { "non_critical_bounce_count", n => { NonCriticalBounceCount = n.GetLongValue(); } },
                { "non_critical_bounce_rate", n => { NonCriticalBounceRate = n.GetLongValue(); } },
                { "non_critical_delay_count", n => { NonCriticalDelayCount = n.GetLongValue(); } },
                { "non_critical_delay_rate", n => { NonCriticalDelayRate = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("classified_failures_count", ClassifiedFailuresCount);
            writer.WriteLongValue("critical_bounce_count", CriticalBounceCount);
            writer.WriteLongValue("critical_bounce_rate", CriticalBounceRate);
            writer.WriteLongValue("critical_delay_count", CriticalDelayCount);
            writer.WriteLongValue("critical_delay_rate", CriticalDelayRate);
            writer.WriteLongValue("delivered_smtp_count", DeliveredSmtpCount);
            writer.WriteLongValue("non_critical_bounce_count", NonCriticalBounceCount);
            writer.WriteLongValue("non_critical_bounce_rate", NonCriticalBounceRate);
            writer.WriteLongValue("non_critical_delay_count", NonCriticalDelayCount);
            writer.WriteLongValue("non_critical_delay_rate", NonCriticalDelayRate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
