// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    /// <summary>Dimension</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GithubComMailgunThresholdsApiDimension
    {
        [EnumMember(Value = "domain")]
        #pragma warning disable CS1591
        Domain,
        #pragma warning restore CS1591
        [EnumMember(Value = "ip")]
        #pragma warning disable CS1591
        Ip,
        #pragma warning restore CS1591
        [EnumMember(Value = "ip_pool")]
        #pragma warning disable CS1591
        Ip_pool,
        #pragma warning restore CS1591
        [EnumMember(Value = "recipient_provider")]
        #pragma warning disable CS1591
        Recipient_provider,
        #pragma warning restore CS1591
        [EnumMember(Value = "subaccount")]
        #pragma warning disable CS1591
        Subaccount,
        #pragma warning restore CS1591
    }
}
