// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    /// <summary>Metric</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GithubComMailgunThresholdsApiSendAlertItemMetric
    {
        [EnumMember(Value = "hard_bounce_rate")]
        #pragma warning disable CS1591
        HardBounceRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "temporary_fail_rate")]
        #pragma warning disable CS1591
        TemporaryFailRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered_rate")]
        #pragma warning disable CS1591
        DeliveredRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "complained_rate")]
        #pragma warning disable CS1591
        ComplainedRate,
        #pragma warning restore CS1591
    }
}
