// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GithubComMailgunDomainsClientGolangDomain : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>URL that a copy of each successfully delivered message is going to be posted to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArchiveTo { get; set; }
#nullable restore
#else
        public string ArchiveTo { get; set; }
#endif
        /// <summary>Timestamp indicating when the domain was created in RFC1123 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Optional field containing additional details about the domain&apos;s disabled status if applicable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunDomainsClientGolangDisabled? Disabled { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunDomainsClientGolangDisabled Disabled { get; set; }
#endif
        /// <summary>If true incoming messages to this domain will be encrypted</summary>
        public bool? EncryptIncomingMessage { get; set; }
        /// <summary>Unique identifier of the domain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Indicates whether the domain is currently disabled</summary>
        public bool? IsDisabled { get; set; }
        /// <summary>Specifies the time-to-live (TTL) in seconds for retrieving both incoming and outgoing messages. The maximum TTL value is determined by your subscription plan</summary>
        public int? MessageTtl { get; set; }
        /// <summary>Fully qualified domain name registered with Mailgun</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>If true Mailgun will only send messages over a TLS connection</summary>
        public bool? RequireTls { get; set; }
        /// <summary>If true Mailgun will not verify the certificate and hostname when setting up a TLS connection</summary>
        public bool? SkipVerification { get; set; }
        /// <summary>SMTP login username for the domain, only present if the user provides an smtp_password. Use the Credentials API for SMTP credentials management</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmtpLogin { get; set; }
#nullable restore
#else
        public string SmtpLogin { get; set; }
#endif
        /// <summary>Optional SMTP password for the domain used for SMTP authentication</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmtpPassword { get; set; }
#nullable restore
#else
        public string SmtpPassword { get; set; }
#endif
        /// <summary>Action to take when a message is flagged as spam. Options are disabled, tag, or block</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpamAction { get; set; }
#nullable restore
#else
        public string SpamAction { get; set; }
#endif
        /// <summary>Current verification status of the domain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The subaccount ID the domain belongs to. This field is only present if the domain is associated with a subaccount</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubaccountId { get; set; }
#nullable restore
#else
        public string SubaccountId { get; set; }
#endif
        /// <summary>Custom tracking host for the domain used for tracking opens and clicks if configured</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrackingHost { get; set; }
#nullable restore
#else
        public string TrackingHost { get; set; }
#endif
        /// <summary>Classification of the domain. Possible values are custom or sandbox</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>If true Mailgun manages DKIM key generation and DNS record configuration automatically</summary>
        public bool? UseAutomaticSenderSecurity { get; set; }
        /// <summary>Subdomain prefix used for open and click tracking</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebPrefix { get; set; }
#nullable restore
#else
        public string WebPrefix { get; set; }
#endif
        /// <summary>Protocol scheme used for tracking</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebScheme { get; set; }
#nullable restore
#else
        public string WebScheme { get; set; }
#endif
        /// <summary>Indicates if the domain is a wildcard domain and can receive emails for any subdomain</summary>
        public bool? Wildcard { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunDomainsClientGolangDomain"/> and sets the default values.
        /// </summary>
        public GithubComMailgunDomainsClientGolangDomain()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunDomainsClientGolangDomain"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunDomainsClientGolangDomain CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunDomainsClientGolangDomain();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archive_to", n => { ArchiveTo = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "disabled", n => { Disabled = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunDomainsClientGolangDisabled>(global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunDomainsClientGolangDisabled.CreateFromDiscriminatorValue); } },
                { "encrypt_incoming_message", n => { EncryptIncomingMessage = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_disabled", n => { IsDisabled = n.GetBoolValue(); } },
                { "message_ttl", n => { MessageTtl = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "require_tls", n => { RequireTls = n.GetBoolValue(); } },
                { "skip_verification", n => { SkipVerification = n.GetBoolValue(); } },
                { "smtp_login", n => { SmtpLogin = n.GetStringValue(); } },
                { "smtp_password", n => { SmtpPassword = n.GetStringValue(); } },
                { "spam_action", n => { SpamAction = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "subaccount_id", n => { SubaccountId = n.GetStringValue(); } },
                { "tracking_host", n => { TrackingHost = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "use_automatic_sender_security", n => { UseAutomaticSenderSecurity = n.GetBoolValue(); } },
                { "web_prefix", n => { WebPrefix = n.GetStringValue(); } },
                { "web_scheme", n => { WebScheme = n.GetStringValue(); } },
                { "wildcard", n => { Wildcard = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("archive_to", ArchiveTo);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.GithubComMailgunDomainsClientGolangDisabled>("disabled", Disabled);
            writer.WriteBoolValue("encrypt_incoming_message", EncryptIncomingMessage);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_disabled", IsDisabled);
            writer.WriteIntValue("message_ttl", MessageTtl);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("require_tls", RequireTls);
            writer.WriteBoolValue("skip_verification", SkipVerification);
            writer.WriteStringValue("smtp_login", SmtpLogin);
            writer.WriteStringValue("smtp_password", SmtpPassword);
            writer.WriteStringValue("spam_action", SpamAction);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("subaccount_id", SubaccountId);
            writer.WriteStringValue("tracking_host", TrackingHost);
            writer.WriteStringValue("type", Type);
            writer.WriteBoolValue("use_automatic_sender_security", UseAutomaticSenderSecurity);
            writer.WriteStringValue("web_prefix", WebPrefix);
            writer.WriteStringValue("web_scheme", WebScheme);
            writer.WriteBoolValue("wildcard", Wildcard);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
