// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Github_com_mailgun_domains_httpapi_CreateDomainResp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Details of the newly created domain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Domain? Domain { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Domain Domain { get; set; }
#endif
        /// <summary>Response message</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>List of DNS records required for receiving emails</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Record>? ReceivingDnsRecords { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Record> ReceivingDnsRecords { get; set; }
#endif
        /// <summary>List of DNS records required for sending emails</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Record>? SendingDnsRecords { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Record> SendingDnsRecords { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_CreateDomainResp"/> and sets the default values.
        /// </summary>
        public Github_com_mailgun_domains_httpapi_CreateDomainResp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_CreateDomainResp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_CreateDomainResp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_CreateDomainResp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "domain", n => { Domain = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Domain>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Domain.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "receiving_dns_records", n => { ReceivingDnsRecords = n.GetCollectionOfObjectValues<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Record>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Record.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sending_dns_records", n => { SendingDnsRecords = n.GetCollectionOfObjectValues<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Record>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Record.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Domain>("domain", Domain);
            writer.WriteStringValue("message", Message);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Record>("receiving_dns_records", ReceivingDnsRecords);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_client_golang_Record>("sending_dns_records", SendingDnsRecords);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
