// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Github_com_mailgun_bounce_classification_internal_api_MetricsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&apos;dimensions&apos; from the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_Dimension?>? Dimensions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_Dimension?> Dimensions { get; set; }
#endif
        /// <summary>&apos;duration&apos; from the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Duration { get; set; }
#nullable restore
#else
        public string Duration { get; set; }
#endif
        /// <summary>&quot;An end timestamp in RFC 2822 format: https://documentation.mailgun.com/docs/mailgun/api-reference/api-overview#date-format&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? End { get; set; }
#nullable restore
#else
        public string End { get; set; }
#endif
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_MetricsItem>? Items { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_MetricsItem> Items { get; set; }
#endif
        /// <summary>The pagination property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_PaginationResp? Pagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_PaginationResp Pagination { get; set; }
#endif
        /// <summary>Resolution of the metrics.</summary>
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_Resolution? Resolution { get; set; }
        /// <summary>&quot;A start timestamp in RFC 2822 format: https://documentation.mailgun.com/docs/mailgun/api-reference/api-overview#date-format&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Start { get; set; }
#nullable restore
#else
        public string Start { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_MetricsResponse"/> and sets the default values.
        /// </summary>
        public Github_com_mailgun_bounce_classification_internal_api_MetricsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_MetricsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_MetricsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_MetricsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dimensions", n => { Dimensions = n.GetCollectionOfEnumValues<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_Dimension>()?.AsList(); } },
                { "duration", n => { Duration = n.GetStringValue(); } },
                { "end", n => { End = n.GetStringValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_MetricsItem>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_MetricsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pagination", n => { Pagination = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_PaginationResp>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_PaginationResp.CreateFromDiscriminatorValue); } },
                { "resolution", n => { Resolution = n.GetEnumValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_Resolution>(); } },
                { "start", n => { Start = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_Dimension>("dimensions", Dimensions);
            writer.WriteStringValue("duration", Duration);
            writer.WriteStringValue("end", End);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_MetricsItem>("items", Items);
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_internal_api_PaginationResp>("pagination", Pagination);
            writer.WriteEnumValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_bounce_classification_entities_Resolution>("resolution", Resolution);
            writer.WriteStringValue("start", Start);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
