// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Github_com_mailgun_domains_httpapi_WebhooksResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Accepted webhook URLs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs? Accepted { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs Accepted { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Clicked webhook URLs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs? Clicked { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs Clicked { get; set; }
#endif
        /// <summary>Complained webhook URLs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs? Complained { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs Complained { get; set; }
#endif
        /// <summary>Delivered webhook URLs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs? Delivered { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs Delivered { get; set; }
#endif
        /// <summary>Opened webhook URLs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs? Opened { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs Opened { get; set; }
#endif
        /// <summary>Permanent fail webhook URLs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs? PermanentFail { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs PermanentFail { get; set; }
#endif
        /// <summary>Temporary fail webhook URLs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs? TemporaryFail { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs TemporaryFail { get; set; }
#endif
        /// <summary>Unsubscribed webhook URLs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs? Unsubscribed { get; set; }
#nullable restore
#else
        public global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs Unsubscribed { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhooksResponse"/> and sets the default values.
        /// </summary>
        public Github_com_mailgun_domains_httpapi_WebhooksResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhooksResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhooksResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhooksResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accepted", n => { Accepted = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs.CreateFromDiscriminatorValue); } },
                { "clicked", n => { Clicked = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs.CreateFromDiscriminatorValue); } },
                { "complained", n => { Complained = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs.CreateFromDiscriminatorValue); } },
                { "delivered", n => { Delivered = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs.CreateFromDiscriminatorValue); } },
                { "opened", n => { Opened = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs.CreateFromDiscriminatorValue); } },
                { "permanent_fail", n => { PermanentFail = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs.CreateFromDiscriminatorValue); } },
                { "temporary_fail", n => { TemporaryFail = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs.CreateFromDiscriminatorValue); } },
                { "unsubscribed", n => { Unsubscribed = n.GetObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>(global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>("accepted", Accepted);
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>("clicked", Clicked);
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>("complained", Complained);
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>("delivered", Delivered);
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>("opened", Opened);
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>("permanent_fail", PermanentFail);
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>("temporary_fail", TemporaryFail);
            writer.WriteObjectValue<global::Soenneker.Mailgun.OpenApiClient.Models.Github_com_mailgun_domains_httpapi_WebhookURLs>("unsubscribed", Unsubscribed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
