// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    /// <summary>If `true`, the certificate and hostname of the resolved MX Host will not be verified when trying to establish a TLS connection. If `false`, Mailgun will verify the certificate and hostname. If either one can not be verified, a TLS connection will not be established. The default is `false`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostV3DomainNameMessagesMultipartFormDataRequestBodyOSkipVerification
    {
        [EnumMember(Value = "yes")]
        #pragma warning disable CS1591
        Yes,
        #pragma warning restore CS1591
        [EnumMember(Value = "no")]
        #pragma warning disable CS1591
        No,
        #pragma warning restore CS1591
        [EnumMember(Value = "true")]
        #pragma warning disable CS1591
        TrueValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "false")]
        #pragma warning disable CS1591
        FalseValue,
        #pragma warning restore CS1591
    }
}
