// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    /// <summary>Webhook type to create.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostV3DomainsDomainWebhooksMultipartFormDataRequestBodyId
    {
        [EnumMember(Value = "accepted")]
        #pragma warning disable CS1591
        Accepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "clicked")]
        #pragma warning disable CS1591
        Clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "opened")]
        #pragma warning disable CS1591
        Opened,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribed")]
        #pragma warning disable CS1591
        Unsubscribed,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "permanent_fail")]
        #pragma warning disable CS1591
        PermanentFail,
        #pragma warning restore CS1591
        [EnumMember(Value = "temporary_fail")]
        #pragma warning disable CS1591
        TemporaryFail,
        #pragma warning restore CS1591
        [EnumMember(Value = "complained")]
        #pragma warning disable CS1591
        Complained,
        #pragma warning restore CS1591
    }
}
