// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    /// <summary>Toggles opens tracking on a per-message basis, see [Tracking Opens](https://documentation.mailgun.com/docs/mailgun/user-manual/tracking-messages/tracking-opens). Has higher priority than domain-level setting.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostV3DomainNameMessagesMimeMultipartFormDataRequestBodyOTrackingOpens
    {
        [EnumMember(Value = "yes")]
        #pragma warning disable CS1591
        Yes,
        #pragma warning restore CS1591
        [EnumMember(Value = "no")]
        #pragma warning disable CS1591
        No,
        #pragma warning restore CS1591
        [EnumMember(Value = "true")]
        #pragma warning disable CS1591
        TrueValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "false")]
        #pragma warning disable CS1591
        FalseValue,
        #pragma warning restore CS1591
    }
}
