// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mailgun.OpenApiClient.Models
{
    /// <summary>Event types to associate with this URL. Use multiple times to specify multiple event types. This replaces the existing associations. </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PUT_v4_domains_domain_webhooks_application_x_www_form_urlencoded_RequestBody_event_types
    {
        [EnumMember(Value = "accepted")]
        #pragma warning disable CS1591
        Accepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "clicked")]
        #pragma warning disable CS1591
        Clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "opened")]
        #pragma warning disable CS1591
        Opened,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribed")]
        #pragma warning disable CS1591
        Unsubscribed,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "permanent_fail")]
        #pragma warning disable CS1591
        Permanent_fail,
        #pragma warning restore CS1591
        [EnumMember(Value = "temporary_fail")]
        #pragma warning disable CS1591
        Temporary_fail,
        #pragma warning restore CS1591
        [EnumMember(Value = "complained")]
        #pragma warning disable CS1591
        Complained,
        #pragma warning restore CS1591
    }
}
