// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.Models;
using Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.Members;
using Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersCsv;
using Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V3.Lists.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\lists\{list_address}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithList_addressItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The members property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.Members.MembersRequestBuilder Members
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The membersCsv property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersCsv.MembersCsvRequestBuilder MembersCsv
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersCsv.MembersCsvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The membersJson property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder MembersJson
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.WithList_addressItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithList_addressItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/lists/{list_address}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.WithList_addressItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithList_addressItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/lists/{list_address}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes a mailing list
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.DeleteV3ListsAddress200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Mailgun.OpenApiClient.Models.DeleteV3ListsAddress404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Mailgun.OpenApiClient.Models.DeleteV3ListsAddress429">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.DeleteV3ListsAddress200?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.DeleteV3ListsAddress200> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Mailgun.OpenApiClient.Models.DeleteV3ListsAddress404.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Mailgun.OpenApiClient.Models.DeleteV3ListsAddress429.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Mailgun.OpenApiClient.Models.DeleteV3ListsAddress200>(requestInfo, global::Soenneker.Mailgun.OpenApiClient.Models.DeleteV3ListsAddress200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the matching mailing list for the given address
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.GetV3ListsAddress200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Mailgun.OpenApiClient.Models.GetV3ListsAddress404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Mailgun.OpenApiClient.Models.GetV3ListsAddress429">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.GetV3ListsAddress200?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.GetV3ListsAddress200> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Mailgun.OpenApiClient.Models.GetV3ListsAddress404.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Mailgun.OpenApiClient.Models.GetV3ListsAddress429.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Mailgun.OpenApiClient.Models.GetV3ListsAddress200>(requestInfo, global::Soenneker.Mailgun.OpenApiClient.Models.GetV3ListsAddress200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update mailing list properties, such as address, description or name
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.PutV3ListsAddress200"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Mailgun.OpenApiClient.Models.PutV3ListsAddress404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Mailgun.OpenApiClient.Models.PutV3ListsAddress429">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.PutV3ListsAddress200?> PutAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.PutV3ListsAddress200> PutAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Mailgun.OpenApiClient.Models.PutV3ListsAddress404.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Mailgun.OpenApiClient.Models.PutV3ListsAddress429.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Mailgun.OpenApiClient.Models.PutV3ListsAddress200>(requestInfo, global::Soenneker.Mailgun.OpenApiClient.Models.PutV3ListsAddress200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes a mailing list
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns the matching mailing list for the given address
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update mailing list properties, such as address, description or name
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "multipart/form-data", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.WithList_addressItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.WithList_addressItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.WithList_addressItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
