// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.V5.Sandbox.Auth_recipients;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V5.Sandbox
{
    /// <summary>
    /// Builds and executes requests for operations under \v5\sandbox
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SandboxRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auth_recipients property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V5.Sandbox.Auth_recipients.Auth_recipientsRequestBuilder Auth_recipients
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V5.Sandbox.Auth_recipients.Auth_recipientsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V5.Sandbox.SandboxRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SandboxRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v5/sandbox", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V5.Sandbox.SandboxRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SandboxRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v5/sandbox", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
