// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.V1.Dkim_management.Domains.Item.Rotate;
using Soenneker.Mailgun.OpenApiClient.V1.Dkim_management.Domains.Item.Rotation;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V1.Dkim_management.Domains.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\dkim_management\domains\{name}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The rotate property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.Dkim_management.Domains.Item.Rotate.RotateRequestBuilder Rotate
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.Dkim_management.Domains.Item.Rotate.RotateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rotation property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.Dkim_management.Domains.Item.Rotation.RotationRequestBuilder Rotation
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.Dkim_management.Domains.Item.Rotation.RotationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V1.Dkim_management.Domains.Item.WithNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/dkim_management/domains/{name}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V1.Dkim_management.Domains.Item.WithNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/dkim_management/domains/{name}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
