// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Entities;
using Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Events;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\bounce-classification\domains\{domain}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDomainItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The entities property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Entities.EntitiesRequestBuilder Entities
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Entities.EntitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.WithDomainItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDomainItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/bounce-classification/domains/{domain}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V1.BounceClassification.Domains.Item.WithDomainItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDomainItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/bounce-classification/domains/{domain}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
