// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\lists\{list_address}\members.json
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MembersJsonRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembersJsonRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/lists/{list_address}/members.json?members={members}{&upsert*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembersJsonRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/lists/{list_address}/members.json?members={members}{&upsert*}", rawUrl)
        {
        }
        /// <summary>
        /// Adds multiple members, up to 1000 per call, to a mailing list, using JSON array format.If the request includes more than 100 entries, the mailing list will be updated asynchronously.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.Models.PostListsListAddressMembersJson200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Mailgun.OpenApiClient.Models.PostListsListAddressMembersJson404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Mailgun.OpenApiClient.Models.PostListsListAddressMembersJson429">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.PostListsListAddressMembersJson200?> PostAsync(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder.MembersJsonRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Mailgun.OpenApiClient.Models.PostListsListAddressMembersJson200> PostAsync(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder.MembersJsonRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Mailgun.OpenApiClient.Models.PostListsListAddressMembersJson404.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Mailgun.OpenApiClient.Models.PostListsListAddressMembersJson429.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Mailgun.OpenApiClient.Models.PostListsListAddressMembersJson200>(requestInfo, global::Soenneker.Mailgun.OpenApiClient.Models.PostListsListAddressMembersJson200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Adds multiple members, up to 1000 per call, to a mailing list, using JSON array format.If the request includes more than 100 entries, the mailing list will be updated asynchronously.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder.MembersJsonRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder.MembersJsonRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Mailgun.OpenApiClient.V3.Lists.Item.MembersJson.MembersJsonRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Adds multiple members, up to 1000 per call, to a mailing list, using JSON array format.If the request includes more than 100 entries, the mailing list will be updated asynchronously.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MembersJsonRequestBuilderPostQueryParameters 
        {
            /// <summary>Mailing list recipients in JSON array format. Can be, either, an array of string addresses or an array of ListMemberRequest JSON objects.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("members")]
            public string? Members { get; set; }
#nullable restore
#else
            [QueryParameter("members")]
            public string Members { get; set; }
#endif
            /// <summary>If true, an existing member will be updated. Defaults to false.</summary>
            [QueryParameter("upsert")]
            public bool? Upsert { get; set; }
        }
    }
}
#pragma warning restore CS0618
