// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mailgun.OpenApiClient.V1.Dkim.Keys;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V1.Dkim
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\dkim
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DkimRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The keys property</summary>
        public global::Soenneker.Mailgun.OpenApiClient.V1.Dkim.Keys.KeysRequestBuilder Keys
        {
            get => new global::Soenneker.Mailgun.OpenApiClient.V1.Dkim.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V1.Dkim.DkimRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DkimRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/dkim", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mailgun.OpenApiClient.V1.Dkim.DkimRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DkimRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/dkim", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
