// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mailgun.OpenApiClient.V1.Keys
{
    /// <summary>&quot;Type of API key (&apos;domain&apos;, &apos;user&apos;, or &apos;web&apos;). Defaults to &apos;user&apos; if not provided. Note: web keys are not subject to IP allowlisting and have a default/maximum validity period of 1 day.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum POSTV1KeysMultipartFormDataRequestBodyPostRequestBody
    {
        [EnumMember(Value = "domain")]
        #pragma warning disable CS1591
        Domain,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "web")]
        #pragma warning disable CS1591
        Web,
        #pragma warning restore CS1591
    }
}
